pipeline{
    agent any
    stages{
        stage("maven"){
            steps{
                sh "mvn clean validate compile install test package"
            }
            post{
                success{
                    echo "Success execution of Maven"
                }
                failure{
                    echo "Fail execution of Maven"
                }
            }
        }
    }
}