pipeline{
    agent any
    tools {
        maven 'M2_HOME'
    }
    stages{
        /*stage("sonar_scan"){
            steps{

                withSonarQubeEnv('sonarQube'){
                    sh "mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar\
                     -Dsonar.projectKey=PolycarpeSI_geolocation "
                }                
            }
            post{
                success{
                    echo "Success scan"
                }
                failure{
                    echo "Fail scan"
                }
            }
        }*/
        stage("maven"){
            steps{
                sh 'rm -rf target/bio*.jar || echo ""'
                sh "mvn clean validate compile install test package"
            }
            post{
                success{
                    echo "Success execution of Maven"
                }
                failure{
                    echo "Fail execution of Maven"
                }
            }
        }
        stage("upload-artifact"){
            steps{
                
                sh 'curl -uadmin:APBZrJk8pn85wcNmx47z1AoGCFp -T \
                target/bio*.jar \
                "http://ec2-54-242-175-136.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
            post{
                success{
                    echo "Success upload artifact"
                }
                failure{
                    echo "Fail upload artifact"
                }
            }
        }
        stage('docker-login'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 099321366213.dkr.ecr.us-east-1.amazonaws.com'
            }
            post{
                success{
                    echo 'Successful login to docker'
                }
                failure{
                    echo 'Fail login to docker'
                }
            }
        }
        stage('docker-build-image'){
            steps{
                //sh 'docker build -t utc-app.v.${BUILD_ID} .'
                sh 'docker build -t web-app .'
            }
            post{
                success{
                    echo "Successful build"
                }
                failure{
                    echo "Fail build"
                }
            }
        }
        stage('docker-tag-image'){
            steps{
                sh 'docker tag web-app:latest 099321366213.dkr.ecr.us-east-1.amazonaws.com/web-app:latest'
                //sh 'docker tag utc-app:latest 099321366213.dkr.ecr.us-east-1.amazonaws.com/utc-app:latest'
                //sh 'docker tag utc-app:latest 099321366213.dkr.ecr.us-east-1.amazonaws.com/utc-app:v.${BUILD_ID}'
                /*sh 'docker tag utc-app-dev:latest \
                099321366213.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                sh 'docker tag utc-app-dev:latest \
                099321366213.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'*/
            }
            post{
                success{
                    echo "Successful tag"
                }
                failure{
                    echo "Fail tag"
                }
            }
        }
        stage('docker-push-image'){
            steps{
                sh 'docker push 099321366213.dkr.ecr.us-east-1.amazonaws.com/web-app:latest'
                //sh 'docker push 099321366213.dkr.ecr.us-east-1.amazonaws.com/utc-app:latest'
                //sh 'docker push 099321366213.dkr.ecr.us-east-1.amazonaws.com/utc-app:v.${BUILD_ID}'
            }
            post{
                success{
                    echo "Successful push"
                }
                failure{
                    echo "Fail push"
                }
            }
        }
    }
}